### ISSUE TITLE
Cannot package project with non-importable dependencies

### ISSUE THREAD

**Issue by Chriscbr** [aws/jsii#3275]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)
- [x] `Go`

### General Information
* **JSII Version:** jsii 1.49.0
* **Platform:** Unix

### What is the problem?

If a JSII project takes a dependency on a package that is not importable, `jsii-pacmak` fails. A package may not be importable if it only provides command-line scripts, for example the [shx](https://www.npmjs.com/package/shx) package. shx does not specify the "main" field in package.json, and it does not have a default "index.js" file that serves as an entrypoint -- its main utility is through the "bin" field which directly runs JS code.

This previously worked, but stopped working when we upgraded our project from JSII v1.47.0 to v1.49.0.

Our use case for taking "non-importable" libraries as dependencies is to bundle them along with our project, so that the command-line scripts in "shx" can be used for functionality in our construct library.

Related issue: https://github.com/projen/projen/pull/1336

### Verbose Log

Reproduction repo: https://github.com/Chriscbr/jsii-pacmak-repro

```
$ npx jsii-pacmak
[jsii-pacmak] [WARN] Exception occurred, not cleaning up
[jsii-pacmak] [WARN] java failed
Error: Cannot find module 'shx'
Require stack:
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/util.js
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/packaging.js
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/npm-modules.js
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/index.js
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/bin/jsii-pacmak.js
- /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/bin/jsii-pacmak
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.findDependencyDirectory (/Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/util.js:18:32)
    at /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/dependency-graph.js:46:42
    at Array.map (<anonymous>)
    at real$traverseDependencyGraph (/Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/dependency-graph.js:45:10)
    at async Object.findLocalBuildDirs (/Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/target.js:76:5)
    at async /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/targets/java.js:171:29
    at async JavaBuilder.generateMavenSettingsForLocalDeps (/Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/targets/java.js:173:51)
    at async /Volumes/workplace/jsii-pacmak-repro/node_modules/jsii-pacmak/lib/targets/java.js:103:1
 ```
