### ISSUE TITLE
compilation error on finding non-existing file since 1.53.0

### ISSUE THREAD

**Issue by zxkane** [aws/jsii#3379]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 
1.53.0 (build c071d26), typescript 3.9.10
* **Platform:**      
Linux 5.4.0-1065-aws ~18.04.1-Ubuntu  2022 x86_64 x86_64 x86_64 GNU/Linux

### What is the problem?

See error when compiling a CDK construct project since 1.53.0.

`error JSII9997: Unknown error: ENOENT: no such file or directory, open '/home/ubuntu/environment/snat/node_modules/aws-cdk-lib/aws-apigateway/test/integ.restapi-import.lit.ts' -- Error: ENOENT: no such file or directory, open '/home/ubuntu/environment/snat/node_modules/aws-cdk-lib/aws-apigateway/test/integ.restapi-import.lit.ts'`

The same code works in previous release, such as 1.52.1.

### Verbose Log

```bash
 npx jsii --silence-warnings=reserved-word --no-fix-peer-dependencies -vvv
[2022-02-10T05:21:27.336] [DEBUG] jsii/package-info - Resolved dependency aws-cdk-lib to /home/ubuntu/environment/snat/node_modules/aws-cdk-lib/.jsii
[2022-02-10T05:21:27.704] [DEBUG] jsii/package-info - Resolved dependency constructs to /home/ubuntu/environment/snat/node_modules/constructs/.jsii
[2022-02-10T05:21:27.706] [DEBUG] jsii/package-info - Resolved dependency constructs to /home/ubuntu/environment/snat/node_modules/constructs/.jsii
[2022-02-10T05:21:27.707] [DEBUG] jsii/compiler - Creating or updating /home/ubuntu/environment/snat/tsconfig.json
error JSII9997: Unknown error: ENOENT: no such file or directory, open '/home/ubuntu/environment/snat/node_modules/aws-cdk-lib/aws-apigateway/test/integ.restapi-import.lit.ts' -- Error: ENOENT: no such file or directory, open '/home/ubuntu/environment/snat/node_modules/aws-cdk-lib/aws-apigateway/test/integ.restapi-import.lit.ts'
```
See the [example project](https://github.com/zxkane/snat/runs/5136020523?check_suite_focus=true) for detail usage.

**Comment by RomainMuller** [comment]
Hey!

Thanks for reporting this. I've been able to reproduce the issue (thanks for pointing to the reproduction, that made it... trivial).

I believe I have identified the root cause of this: the compiler is un-necessarily trying to re-render the `README.md` file from dependencies (in this case `aws-cdk-lib`), which fails because early versions of `aws-cdk-lib` don't include the `.lit.ts` files that the `README.md` file refers to.

Since this work is unnecessary for dependencies, it should simply not be attempted. I'll prepare a PR to this effect.
