### ISSUE TITLE
Lazy still broken in Python

### ISSUE THREAD

**Issue by serverlessunicorn** [aws/jsii#1781]
## :bug: Bug Report
The following fails on CDK 1.49.1:
        class Foo:
            def produce(me, context):
                return self.api.rest_api_id
        lazy = core.Lazy.string_value(Foo())
with the error: AttributeError: type object 'Foo' has no attribute '__jsii_type__'

Possibly recurrence or variant of 807 (https://github.com/aws/jsii/issues/807)
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:**  CDK version is 1.49.1
* **Platform:**      Darwin MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### What is the problem?

Lazy in AWS CDK Python appears to have a jsii serialization problem; see discussion in 807.
### Verbose Log

Traceback (most recent call last):
  File "deploy.py", line 80, in <module>
    deployer.deploy()
  File "deploy.py", line 63, in deploy
    cdk = cdkstack.CdkStack(scope=app, id='VendiaShareDeployer',
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/timwagner/Desktop/projects/vendia/src/share/server/deploy/cdkstack.py", line 32, in __init__
    lazy = core.Lazy.string_value(Foo())
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6313, in string_value
    return jsii.sinvoke(cls, "stringValue", [producer, options])
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 311, in sinvoke
    args=_make_reference_for_native(self, args),
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 124, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 124, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 151, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/timwagner/Desktop/projects/vendia/src/share/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 226, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'Foo' has no attribute '__jsii_type__'

**Comment by serverlessunicorn** [comment]
Ah, so perhaps this is an AWS CDK issue: The example at https://docs.aws.amazon.com/cdk/latest/guide/tokens.html (with Python selected) fails as written, but if you use the example from #807 and add @jsii.implements(core.IStringProducer) as an annotation to the producing class, it succeeds with the workaround.

**Comment by mschwab12** [comment]
This seems stil an issue. Can you reopen this bug?

**Comment by mrgrain** [comment]
Tested this on the latest versions (aws-cdk-lib 2.258.1, jsii 1.134.0) — the behavior is unchanged. Plain Python classes still throw `AttributeError: type object 'Foo' has no attribute '__jsii_type__'`.

The workaround is to use the `@jsii.implements()` decorator as documented in the [jsii Python guide](https://aws.github.io/jsii/user-guides/lib-user/language-specific/python/#implementing-interfaces):

```python
import jsii
import aws_cdk as cdk

@jsii.implements(cdk.IStableStringProducer)
class MyStringProducer:
    def produce(self):
        return "hello-from-lazy"

lazy_string = cdk.Lazy.string(MyStringProducer())
```

The `@jsii.implements()` decorator is required because jsii does not support Python's duck typing — interfaces must be explicitly registered on the class metadata for serialization across the jsii kernel boundary.
