### ISSUE TITLE
process.terminate() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by camilobermudez85** [aws/jsii#2398]
### Affected Languages

- [X] `Python`

### General Information
* **JSII Version:** 1.16.0
* **Platform:** Debian

### What is the problem?
Hey, guys. While running **cdk diff** on a **python 3.7.6** app I'm getting the next error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 293, in stop
    self._process.wait(timeout=5)
  File "/usr/local/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 1645, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['node', '/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js']' timed out after 5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 296, in stop
    self._process.terminate(timeout=5)
TypeError: terminate() got an unexpected keyword argument 'timeout'
```

The problem seems to be caused by [this change](https://github.com/aws/jsii/commit/c11999499e6f9679da0272d96a1422025bbc0502#diff-93240363d8ef76db5d41bb9017a4be449538459dff102c009f87f0996bbb55f6R296)  introduced in PR #2100:

![image](https://user-images.githubusercontent.com/7834055/103581559-3ffec480-4eaa-11eb-850a-51b06633f3a1.png)

Indeed, _timeout_ is not a valid parameter for that method, perhaps removing it should be enough to fix the issue. Thanks a lot!

@RomainMuller

**Comment by jhzab** [comment]
I'm also running into the timeout when using _cdk synth_.

Running under Ubuntu 20.04 on WSL1.
aws-cdk version (python modules and nodejs cli tool): 1.82.0
nodejs version: 14.15.4 (but also tried with 10.x and 12.x)
python version: 3.8.5

Steps to reproduce:
- `mkdir sftest`
- `cd sftest`
- `cdk init sample-app --language=python`
- Add aws-cdk.aws_stepfunctions_tasks==1.82.0 to install_requires and install dependencies (do not install the sftest package :-) )
- Add `from aws_cdk import aws_stepfunctions_tasks as sfn_tasks` to the stack under sftest/sftest_stack.py
- Run `cdk synth`
- Error will be at the top of the output

Error appears only with the import. Hope the information is helpful.

**Comment by RomainMuller** [comment]
Oh jeez. Yeah I'll get a fix out ASAP.

**Comment by RomainMuller** [comment]
This ought to be solved by release 1.17.1 of the jsii runtime library, which should be available already (`pip install --upgrade jsii` should do the magic)

**Comment by RomainMuller** [comment]
@all-contributors add @camilobermudez85  for bug

**Comment by camilobermudez85** [comment]
> This ought to be solved by release 1.17.1 of the jsii runtime library, which should be available already (`pip install --upgrade jsii` should do the magic)

@RomainMuller Thanks a lot!
