### PR TITLE
fix(python): process.terminate() got an unexpected keyword argument 'timeout'

### LINKED ISSUE #2398: process.terminate() got an unexpected keyword argument 'timeout'
### Affected Languages

- [X] `Python`

### General Information
* **JSII Version:** 1.16.0
* **Platform:** Debian

### What is the problem?
Hey, guys. While running **cdk diff** on a **python 3.7.6** app I'm getting the next error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 293, in stop
    self._process.wait(timeout=5)
  File "/usr/local/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 1645, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['node', '/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js']' timed out after 5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 296, in stop
    self._process.terminate(timeout=5)
TypeError: terminate() got an unexpected keyword argument 'timeout'
```

The problem seems to be caused by [this change](https://github.com/aws/jsii/commit/c11999499e6f9679da0272d96a1422025bbc0502#diff-93240363d8ef76db5d41bb9017a4be449538459dff102c009f87f0996bbb55f6R296)  introduced in PR #2100:

image

Indeed, _timeout_ is not a valid parameter for that method, perhaps removing it should be enough to fix the issue. Thanks a lot!

@RomainMuller

### PR DESCRIPTION
**Pull request by RomainMuller**
Corrected usage of `process.terminate` to remove unexpected `timeout`
argument. Not sure how this did not surface in integration tests (will
investigate later).

Fixes #2398

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py [hunk 1]
```diff
@@ -298,10 +298,7 @@ def stop(self):
         try:
             self._process.wait(timeout=5)
         except subprocess.TimeoutExpired:
-            try:
-                self._process.terminate(timeout=5)
-            except subprocess.TimeoutExpired:
-                self._process.kill()
+            self._process.terminate()
```
Comment (RomainMuller) [inline packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py:301]: Note: `terminate` does the same work as `kill`, except on POSIX platforms, where the signal sent to the subprocess is different (`SIGTERM` for `terminate`, `SIGKILL` for `kill`). The default handling for both of these signals is the same (terminates the process).

`SIGKILL` cannot be trapped (always kills the process immediately, not giving it a chance to clean up after itself).

`SIGTERM` can be trapped (and rescued to not terminate the process), and gives the process a modest slice of time to clean up after itself. Since we are not trapping `SIGTERM`, both signals achieve the same - terminating the `node` VM, except `SIGTERM` would allow VM exit handlers to run, which is desirable.

**Review by iliapolo — APPROVED** [review]
